function h = renderTree(BezStruct)
%RENDERTREE Summary of this function goes here
%   Detailed explanation goes here
% INPUTS:
%   BezStruct   --  1xn Structure Array generated by TreeGen() which
%                   contains Bezier curve in the 'curve' field
% OUTPUTS:
%   h           --  Handle of the figure created 
    figure; hold on;
    for gen = 1:length(BezStructure)
%      'gen' is generation number of the Bezier Structure
       
        
        
    end
end

