function h = renderTree(BezStruct)
%RENDERTREE Summary of this function goes here
%   Detailed explanation goes here
% INPUTS:
%   BezStruct   --  1xn Structure Array generated by TreeGen() which
%                   contains Bezier curve in the 'curve' field
% OUTPUTS:
%   h           --  Handle of the figure created 

    h = figure; hold on;
    for gen = 1:length(BezStruct)
%      'gen' is generation number of the Bezier Structure
       curveMat = BezStruct(gen).curve;
       xMat = squeeze(curveMat(1,:,:));
       yMat = squeeze(curveMat(2,:,:));
       zMat = squeeze(curveMat(3,:,:));
       plot3(xMat,yMat,zMat);
    end
end

